config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include AvatarUploader::Attachment(:avatar)

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Authorization
  include BulletHelper

  protect_from_forgery with: :exception

  responders :flash
  respond_to :html
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper do
      def current_user
        super.decorate if user_signed_in?
      end
    end
  end

  private

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    rescue_from ActionPolicy::Unauthorized, with: :user_not_authorized
  end

  private

  def user_not_authorized
    redirect_to(root_path)
  end
end

app/controllers/concerns/bullet_helper.rb
module BulletHelper
  def skip_bullet
    return unless defined?(Bullet)
    return unless Bullet.enable?

    # Can't use `Bullet.enable=` b/c it's resets settings
    # https://github.com/flyerhzm/bullet/blob/master/lib/bullet.rb#L48-L58
    Bullet.instance_variable_set :@enable, false

    yield
  ensure
    Bullet.instance_variable_set :@enable, true
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    protected

    def update_resource(resource, params)
      resource.update(params)
    end

    def account_update_params
      params = devise_parameter_sanitizer.sanitize(:account_update)

      if passwords_blank?(params)
        params.except(:password, :password_confirmation)
      else
        params
      end
    end

    def passwords_blank?(params)
      params[:password].blank? && params[:password_confirmation].blank?
    end
  end
end

app/views/application/_footer.html.slim
footer.grid-container
  .cell
    p &copy; Flatstack #{Time.zone.today.year}

app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(class="callout #{type}" data-closable)
    = content
    button.close-button(tabindex="0" aria-label="Dismiss alert" type="button" data-close)
      span aria-hidden="true" &times;

app/views/application/_navigation.html.slim
.title-bar data-hide-for="medium" data-responsive-toggle="navigation_menu"
  button.menu-icon data-toggle="" type="button"
  title-bar-title Menu

nav.top-bar#navigation_menu
  = render "navigation_main"
  = render "navigation_user"

app/views/application/_navigation_main.html.slim
.top-bar-left
  ul.menu
    li
      = link_to "Rails Base example site", root_path
      = active_link_to("Home", root_path, active: :exclusive, wrap_tag: :li) if user_signed_in?

app/views/application/_navigation_user.html.slim
ul.top-bar-right.menu.dropdown(data-dropdown-menu)
  - if user_signed_in?
    li
      a = current_user.full_name
      ul.menu
        li = link_to "Edit profile", edit_user_registration_path
        li = link_to "Sign out", destroy_user_session_path
  - else
    = active_link_to "Sign in", new_user_session_path, active: :exclusive, wrap_tag: :li
    = active_link_to "Sign up", new_user_registration_path, active: :exclusive, wrap_tag: :li

app/views/layouts/application.html.slim
doctype html

html class="no-js" lang="en"

  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="robots" content="NOODP,NOYDIR"

    = display_meta_tags site: "RailsBase", keywords: %w[title site]
    = csrf_meta_tags

    = stylesheet_link_tag :application

    == analytics_init if GoogleAnalytics.valid_tracker?

  body
    = render "navigation"
    = render "messages"

    main.grid-container
      = yield

    = render "footer"

    = javascript_pack_tag :application
    = javascript_include_tag :application

app/views/pages/home.html.slim
.grid-x
  .cell
    | Hello,
    =< current_user&.full_name_with_email || "World"
    | !

app/views/users/shared/_links.html.slim
h6 Anything else?
ul.no-bullet
  - if controller_name != "sessions"
    li = link_to "Sign in", new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != "registrations"
    li = link_to "Create a new account", new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != "passwords"
    li = link_to "Forgot your password?", new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != "confirmations"
    li = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
    li = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)